# Generated by Django 2.1.3 on 2018-12-30 16:26

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_domaine', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=255, unique=True)),
                ('slug_service', models.SlugField(unique=True)),
                ('description_service', models.TextField()),
                ('image_service', models.ImageField(blank=True, null=True, upload_to=services.models.service_directory_path)),
                ('domain_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Domain')),
            ],
        ),
    ]
