# Generated by Django 2.1.3 on 2018-12-31 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_service_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='medayor_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='nom_service',
            field=models.CharField(max_length=255, unique=True, verbose_name=''),
        ),
    ]
