# Generated by Django 2.1.3 on 2018-12-31 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='nom_service',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
