# Generated by Django 2.1.3 on 2019-01-01 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20181231_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='slug_service',
            new_name='slug',
        ),
    ]
