# Generated by Django 2.1.3 on 2019-01-01 01:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190101_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='definition_service',
            field=models.TextField(default=datetime.datetime(2019, 1, 1, 1, 30, 18, 839077, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
