# Generated by Django 2.1.3 on 2019-01-01 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_definition_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='definition_service',
        ),
    ]
