# Generated by Django 2.1.3 on 2019-01-04 13:36

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_user_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_directory_path)),
                ('mission', models.CharField(max_length=255)),
                ('is_team', models.BooleanField(default=False)),
                ('team_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
