# Generated by Django 2.1.3 on 2019-01-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_user',
            new_name='user',
        ),
    ]
