# Generated by Django 2.1.3 on 2019-01-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190104_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='firsname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
