# Generated by Django 2.1.3 on 2018-12-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
