# Generated by Django 2.1.3 on 2018-12-31 12:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_project',
            field=models.ImageField(default=datetime.datetime(2018, 12, 31, 12, 10, 9, 469273, tzinfo=utc), upload_to='projects'),
            preserve_default=False,
        ),
    ]
